<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Http\Action\Profile\ChangePasswordProcessAction' shared autowired service.

return $this->services['OpenCFP\Http\Action\Profile\ChangePasswordProcessAction'] = new \OpenCFP\Http\Action\Profile\ChangePasswordProcessAction(${($_ = isset($this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication']) ? $this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication'] : $this->getSentinelAuthenticationService()) && false ?: '_'}, ${($_ = isset($this->services['HTMLPurifier']) ? $this->services['HTMLPurifier'] : $this->getHTMLPurifierService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
