<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Http\Action\Talk\CreateAction' shared autowired service.

return $this->services['OpenCFP\Http\Action\Talk\CreateAction'] = new \OpenCFP\Http\Action\Talk\CreateAction(${($_ = isset($this->services['OpenCFP\Http\View\TalkHelper']) ? $this->services['OpenCFP\Http\View\TalkHelper'] : $this->getTalkHelperService()) && false ?: '_'}, ${($_ = isset($this->services['OpenCFP\Domain\CallForPapers']) ? $this->services['OpenCFP\Domain\CallForPapers'] : $this->getCallForPapersService()) && false ?: '_'}, ${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
