<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Http\Action\Reviewer\DashboardAction' shared autowired service.

return $this->services['OpenCFP\Http\Action\Reviewer\DashboardAction'] = new \OpenCFP\Http\Action\Reviewer\DashboardAction(${($_ = isset($this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication']) ? $this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication'] : $this->getSentinelAuthenticationService()) && false ?: '_'}, ${($_ = isset($this->services['OpenCFP\Domain\Talk\TalkFormatter']) ? $this->services['OpenCFP\Domain\Talk\TalkFormatter'] : $this->services['OpenCFP\Domain\Talk\TalkFormatter'] = new \OpenCFP\Domain\Talk\TalkFormatter()) && false ?: '_'});
