<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Http\Action\Talk\DeleteAction' shared autowired service.

return $this->services['OpenCFP\Http\Action\Talk\DeleteAction'] = new \OpenCFP\Http\Action\Talk\DeleteAction(${($_ = isset($this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication']) ? $this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication'] : $this->getSentinelAuthenticationService()) && false ?: '_'}, ${($_ = isset($this->services['OpenCFP\Domain\CallForPapers']) ? $this->services['OpenCFP\Domain\CallForPapers'] : $this->getCallForPapersService()) && false ?: '_'});
