<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Http\Action\Talk\EditAction' shared autowired service.

return $this->services['OpenCFP\Http\Action\Talk\EditAction'] = new \OpenCFP\Http\Action\Talk\EditAction(${($_ = isset($this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication']) ? $this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication'] : $this->getSentinelAuthenticationService()) && false ?: '_'}, ${($_ = isset($this->services['OpenCFP\Http\View\TalkHelper']) ? $this->services['OpenCFP\Http\View\TalkHelper'] : $this->getTalkHelperService()) && false ?: '_'}, ${($_ = isset($this->services['OpenCFP\Domain\CallForPapers']) ? $this->services['OpenCFP\Domain\CallForPapers'] : $this->getCallForPapersService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
