<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'OpenCFP\Infrastructure\Event\ExceptionListener' shared autowired service.

return $this->services['OpenCFP\Infrastructure\Event\ExceptionListener'] = new \OpenCFP\Infrastructure\Event\ExceptionListener();
