<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Http\Action\Page\HomePageAction' shared autowired service.

return $this->services['OpenCFP\Http\Action\Page\HomePageAction'] = new \OpenCFP\Http\Action\Page\HomePageAction(false);
