<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'OpenCFP\Infrastructure\CacheWarmer\HtmlPurifierWarmer' shared autowired service.

return $this->services['OpenCFP\Infrastructure\CacheWarmer\HtmlPurifierWarmer'] = new \OpenCFP\Infrastructure\CacheWarmer\HtmlPurifierWarmer(${($_ = isset($this->services['filesystem']) ? $this->services['filesystem'] : $this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem()) && false ?: '_'});
