<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Http\Action\Reviewer\Talk\IndexAction' shared autowired service.

return $this->services['OpenCFP\Http\Action\Reviewer\Talk\IndexAction'] = new \OpenCFP\Http\Action\Reviewer\Talk\IndexAction(${($_ = isset($this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication']) ? $this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication'] : $this->getSentinelAuthenticationService()) && false ?: '_'}, ${($_ = isset($this->services['OpenCFP\Domain\Talk\TalkFilter']) ? $this->services['OpenCFP\Domain\Talk\TalkFilter'] : $this->load(__DIR__.'/getTalkFilterService.php')) && false ?: '_'});
