<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Http\Action\Reviewer\Speaker\IndexAction' shared autowired service.

return $this->services['OpenCFP\Http\Action\Reviewer\Speaker\IndexAction'] = new \OpenCFP\Http\Action\Reviewer\Speaker\IndexAction(${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'});
