<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Domain\Services\IdentityProvider' shared autowired service.

return $this->services['OpenCFP\Domain\Services\IdentityProvider'] = new \OpenCFP\Infrastructure\Auth\SentinelIdentityProvider(${($_ = isset($this->services['Cartalyst\Sentinel\Sentinel']) ? $this->services['Cartalyst\Sentinel\Sentinel'] : $this->getSentinelService()) && false ?: '_'}, new \OpenCFP\Infrastructure\Repository\IlluminateUserRepository(new \OpenCFP\Domain\Model\User()));
