<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Http\Action\Admin\Speaker\PromoteAction' shared autowired service.

return $this->services['OpenCFP\Http\Action\Admin\Speaker\PromoteAction'] = new \OpenCFP\Http\Action\Admin\Speaker\PromoteAction(${($_ = isset($this->services['OpenCFP\Domain\Services\AccountManagement']) ? $this->services['OpenCFP\Domain\Services\AccountManagement'] : $this->getAccountManagementService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
