<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Http\Controller\ProfileController' shared autowired service.

return $this->services['OpenCFP\Http\Controller\ProfileController'] = new \OpenCFP\Http\Controller\ProfileController(${($_ = isset($this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication']) ? $this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication'] : $this->getSentinelAuthenticationService()) && false ?: '_'}, ${($_ = isset($this->services['HTMLPurifier']) ? $this->services['HTMLPurifier'] : $this->getHTMLPurifierService()) && false ?: '_'}, new \OpenCFP\Domain\Services\ProfileImageProcessor('/application/web/uploads', new \OpenCFP\Infrastructure\Crypto\PseudoRandomStringGenerator()), ${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, new \OpenCFP\Path('/application'));
