<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'OpenCFP\Http\Form\ResetForm' shared autowired service.

return $this->services['OpenCFP\Http\Form\ResetForm'] = \OpenCFP\Http\Form\FormFactory::create(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load(__DIR__.'/getForm_FactoryService.php')) && false ?: '_'}, 'OpenCFP\\Http\\Form\\ResetFormType');
