<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Http\Action\Forgot\ResetProcessAction' shared autowired service.

return $this->services['OpenCFP\Http\Action\Forgot\ResetProcessAction'] = new \OpenCFP\Http\Action\Forgot\ResetProcessAction(${($_ = isset($this->services['OpenCFP\Http\Form\ResetForm']) ? $this->services['OpenCFP\Http\Form\ResetForm'] : $this->load(__DIR__.'/getResetFormService.php')) && false ?: '_'}, ${($_ = isset($this->services['OpenCFP\Domain\Services\AccountManagement']) ? $this->services['OpenCFP\Domain\Services\AccountManagement'] : $this->getAccountManagementService()) && false ?: '_'}, ${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
