<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'OpenCFP\Application\Speakers' shared autowired service.

return $this->services['OpenCFP\Application\Speakers'] = new \OpenCFP\Application\Speakers(${($_ = isset($this->services['OpenCFP\Domain\Services\IdentityProvider']) ? $this->services['OpenCFP\Domain\Services\IdentityProvider'] : $this->load(__DIR__.'/getIdentityProviderService.php')) && false ?: '_'});
