<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Http\Controller\Admin\SpeakersController' shared autowired service.

return $this->services['OpenCFP\Http\Controller\Admin\SpeakersController'] = new \OpenCFP\Http\Controller\Admin\SpeakersController(${($_ = isset($this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication']) ? $this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication'] : $this->getSentinelAuthenticationService()) && false ?: '_'}, ${($_ = isset($this->services['OpenCFP\Domain\Services\AccountManagement']) ? $this->services['OpenCFP\Domain\Services\AccountManagement'] : $this->getAccountManagementService()) && false ?: '_'}, new \OpenCFP\Domain\Model\Airport(), ${($_ = isset($this->services['wouterj_eloquent']) ? $this->services['wouterj_eloquent'] : $this->load(__DIR__.'/getWouterjEloquentService.php')) && false ?: '_'}, ${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, 'BSB', 1523664000, 1523750400);
