<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'OpenCFP\Domain\Talk\TalkFormatter' shared autowired service.

return $this->services['OpenCFP\Domain\Talk\TalkFormatter'] = new \OpenCFP\Domain\Talk\TalkFormatter();
