<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'OpenCFP\Domain\Talk\TalkFilter' shared autowired service.

return $this->services['OpenCFP\Domain\Talk\TalkFilter'] = new \OpenCFP\Domain\Talk\TalkFilter(${($_ = isset($this->services['OpenCFP\Domain\Talk\TalkFormatter']) ? $this->services['OpenCFP\Domain\Talk\TalkFormatter'] : $this->services['OpenCFP\Domain\Talk\TalkFormatter'] = new \OpenCFP\Domain\Talk\TalkFormatter()) && false ?: '_'}, new \OpenCFP\Domain\Model\Talk());
