<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'OpenCFP\Domain\Talk\TalkHandler' shared autowired service.

$a = ${($_ = isset($this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication']) ? $this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication'] : $this->getSentinelAuthenticationService()) && false ?: '_'};

return $this->services['OpenCFP\Domain\Talk\TalkHandler'] = new \OpenCFP\Domain\Talk\TalkHandler($a, new \OpenCFP\Domain\Services\TalkRating\YesNoRating(new \OpenCFP\Domain\Model\TalkMeta(), $a));
