<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Http\Action\Talk\UpdateAction' shared autowired service.

return $this->services['OpenCFP\Http\Action\Talk\UpdateAction'] = new \OpenCFP\Http\Action\Talk\UpdateAction(${($_ = isset($this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication']) ? $this->services['OpenCFP\Infrastructure\Auth\SentinelAuthentication'] : $this->getSentinelAuthenticationService()) && false ?: '_'}, ${($_ = isset($this->services['OpenCFP\Http\View\TalkHelper']) ? $this->services['OpenCFP\Http\View\TalkHelper'] : $this->getTalkHelperService()) && false ?: '_'}, ${($_ = isset($this->services['OpenCFP\Domain\CallForPapers']) ? $this->services['OpenCFP\Domain\CallForPapers'] : $this->getCallForPapersService()) && false ?: '_'}, ${($_ = isset($this->services['HTMLPurifier']) ? $this->services['HTMLPurifier'] : $this->getHTMLPurifierService()) && false ?: '_'}, ${($_ = isset($this->services['swiftmailer.mailer.default']) ? $this->services['swiftmailer.mailer.default'] : $this->load(__DIR__.'/getSwiftmailer_Mailer_DefaultService.php')) && false ?: '_'}, ${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, 'cgrandval@darkmira.com.br', 'Darkmira Tour PHP 2018', 'Jan. 18th, 2018');
