<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'OpenCFP\Http\Action\Talk\ViewAction' shared autowired service.

return $this->services['OpenCFP\Http\Action\Talk\ViewAction'] = new \OpenCFP\Http\Action\Talk\ViewAction(${($_ = isset($this->services['OpenCFP\Application\Speakers']) ? $this->services['OpenCFP\Application\Speakers'] : $this->load(__DIR__.'/getSpeakersService.php')) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
