<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'wouterj_eloquent.aliases.loader' shared service.

return $this->services['wouterj_eloquent.aliases.loader'] = new \WouterJ\EloquentBundle\Facade\AliasesLoader();
