<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'wouterj_eloquent.migrations.creator' shared service.

return $this->services['wouterj_eloquent.migrations.creator'] = new \WouterJ\EloquentBundle\Migrations\Creator();
