<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'wouterj_eloquent.migrator' shared service.

return $this->services['wouterj_eloquent.migrator'] = new \WouterJ\EloquentBundle\Migrations\Migrator(${($_ = isset($this->services['wouterj_eloquent.migrations.repository']) ? $this->services['wouterj_eloquent.migrations.repository'] : $this->load(__DIR__.'/getWouterjEloquent_Migrations_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['wouterj_eloquent.database_manager']) ? $this->services['wouterj_eloquent.database_manager'] : $this->load(__DIR__.'/getWouterjEloquent_DatabaseManagerService.php')) && false ?: '_'});
