<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'wouterj_eloquent.commands.seed' shared service.

$this->services['wouterj_eloquent.commands.seed'] = $instance = new \WouterJ\EloquentBundle\Command\SeedCommand($this, ${($_ = isset($this->services['wouterj_eloquent.database_manager']) ? $this->services['wouterj_eloquent.database_manager'] : $this->load(__DIR__.'/getWouterjEloquent_DatabaseManagerService.php')) && false ?: '_'}, $this->parameters['kernel.bundles'], 'production');

$instance->setName('eloquent:seed');

return $instance;
