<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'wouterj_eloquent' shared service.

$this->services['wouterj_eloquent'] = $instance = new \Illuminate\Database\Capsule\Manager();

$instance->setEventDispatcher(${($_ = isset($this->services['wouterj_eloquent.events']) ? $this->services['wouterj_eloquent.events'] : $this->load(__DIR__.'/getWouterjEloquent_EventsService.php')) && false ?: '_'});
$instance->addConnection(array('driver' => 'mysql', 'host' => '127.0.0.1', 'database' => 'php_096_cfp_20', 'username' => 'cfp_dmt_394_php', 'password' => 'ktR{MrrergETxir7N;U;vJEz3uDjJhA9QNzXv8ng', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => null, 'port' => null), 'default');

return $instance;
