<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'wouterj_eloquent.commands.seed_make' shared service.

$this->services['wouterj_eloquent.commands.seed_make'] = $instance = new \WouterJ\EloquentBundle\Command\SeederMakeCommand('/application', $this->parameters['kernel.bundles']);

$instance->setName('eloquent:make:seeder');

return $instance;
