<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'wouterj_eloquent.migrations.repository' shared service.

return $this->services['wouterj_eloquent.migrations.repository'] = new \Illuminate\Database\Migrations\DatabaseMigrationRepository(${($_ = isset($this->services['wouterj_eloquent.database_manager']) ? $this->services['wouterj_eloquent.database_manager'] : $this->load(__DIR__.'/getWouterjEloquent_DatabaseManagerService.php')) && false ?: '_'}, 'migrations');
