<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'wouterj_eloquent.commands.migrate_install' shared service.

$this->services['wouterj_eloquent.commands.migrate_install'] = $instance = new \WouterJ\EloquentBundle\Command\MigrateInstallCommand(${($_ = isset($this->services['wouterj_eloquent.migrations.repository']) ? $this->services['wouterj_eloquent.migrations.repository'] : $this->load(__DIR__.'/getWouterjEloquent_Migrations_RepositoryService.php')) && false ?: '_'});

$instance->setName('eloquent:migrate:install');

return $instance;
