<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'wouterj_eloquent.form.type_guesser' shared service.

return $this->services['wouterj_eloquent.form.type_guesser'] = new \WouterJ\EloquentBundle\Form\EloquentModelTypeGuesser();
