<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'wouterj_eloquent.facade.initializer' shared service.

return $this->services['wouterj_eloquent.facade.initializer'] = new \WouterJ\EloquentBundle\EventListener\FacadeInitializer($this);
