<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHcl3agw\OpenCFPProductionProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHcl3agw/OpenCFPProductionProjectContainer.php') {
    touch(__DIR__.'/ContainerHcl3agw.legacy');

    return;
}

if (!\class_exists(OpenCFPProductionProjectContainer::class, false)) {
    \class_alias(\ContainerHcl3agw\OpenCFPProductionProjectContainer::class, OpenCFPProductionProjectContainer::class, false);
}

return new \ContainerHcl3agw\OpenCFPProductionProjectContainer();
